version: "3.9"

networks:
  default:
    external: true
    name: traefik

services:
    pile:
        image: docker.heinrichhartmann.net/pile
        volumes:
        - /svc/mnt/pile/pile:/pile/data/pile
        - /svc/mnt/pile/stack:/pile/data/stack
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pile.rule=HostRegexp(`pile.{domain:.*}`)"
        - "traefik.http.routers.pile.entrypoints=https"
        - "traefik.http.routers.pile.tls=true"
        - "traefik.http.routers.pile.middlewares=auth@file"
        - "traefik.http.services.pile.loadbalancer.server.port=8080"
        command: piled
