version: "3.9"

networks:
  default:
    external: true
    name: traefik

services:
  amp:
    image: rain0r/ampd
    environment:
      - MPD_SERVER=hifipi.ts.heinrichhartmann.net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.amp.rule=HostRegexp(`amp.{domain:.*}`)"
      - "traefik.http.routers.amp.entrypoints=https"
      - "traefik.http.routers.amp.tls=true"
