{
 "title": "Hosts",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "prom_container",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total,name)"
    }
   },
   {
    "name": "container",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Service Availability",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{routing=\"internal\"}\n\n\n",
     "legendFormat": "{{humanname}}"
    }
   ]
  },
  { "title": "Global Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Host Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "External connectivity",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-ping\"}\n\n\n",
     "legendFormat": "{{humanname}}"
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate({source=\"docker\", container_name=~\"$prom_container\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate({source=\"docker\"}[$__interval]) * 60",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Docke continer logs ($prom_container)",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "{source=\"docker\", container_name=~\"$prom_container\"} | json | line_format \"{{.container_name}} | {{.body}}\""
    }
   ]
  },
  {
   "title": "Docker Events",
   "type": "logs",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "{source=\"systemd\", fluent_tag=\"journal.docker-events.service\" } | json | line_format \"{{.attributes_MESSAGE}}\" |  json | Actor_Attributes_name =~ \"$prom_container\" | line_format \"{{.Actor_Attributes_name}} | {{.Action}}\""
    }
   ]
  },
  {
   "title": "Container CPU",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (name) (sum without (dc,from,id) (irate(container_cpu_user_seconds_total[$__interval]) * 100))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container CPU",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (sum without (dc,from,id) (container_memory_usage_bytes - container_memory_cache))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Systemd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Systemd Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum by (fluent_tag) (rate({ source=\"systemd\"} [$__interval]) * 60)",
     "legendFormat": "{{fluent_tag}}"
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate({source=\"systemd\"}[$__interval]) * 60",
     "legendFormat": "{{ fluent_tag }}"
    }
   ]
  },
  {
   "title": "Systemd Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "{source=\"systemd\"}  | json | line_format \"[{{.attributes__SYSTEMD_UNIT}}] {{.attributes_MESSAGE}}\""
    }
   ]
  },
  {
   "title": "LAN ICMP Availability",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "sum by (instance) (probe_success{job=\"blackbox-ping-lan\"}) > 0 unless sum without (instance) (probe_success{job=\"blackbox-ping-lan\"} == 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}