version: "3.9"

networks:
  default:
    external: true
    name: traefik

volumes:
  music_data:
    driver: local

services:
  music:
    image: airsonic/airsonic
    volumes:
      - /share/hhartmann/var/airsonic/data:/airsonic/data
      - /share/hhartmann/var/airsonic/playlists:/airsonic/playlists
      - /share/hhartmann/var/airsonic/podcasts:/airsonic/podcasts
      - /share/hhartmann/attic/Music:/airsonic/music/Music:ro
      - /share/hhartmann/garage/Videos:/airsonic/music/Videos:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.music.rule=HostRegexp(`music.{domain:.*}`)"
      - "traefik.http.routers.music.entrypoints=https"
      - "traefik.http.routers.music.tls=true"
      - "traefik.http.services.music.loadbalancer.server.port=4040"
    networks:
      - default

  mstream:
    image: lscr.io/linuxserver/mstream:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - music_data:/config
      - /share/hhartmann/attic/Music:/music:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mstream.rule=HostRegexp(`mstream.{domain:.*}`)"
      - "traefik.http.routers.mstream.entrypoints=https"
      - "traefik.http.routers.mstream.tls=true"
      - "traefik.http.services.mstream.loadbalancer.server.port=3000"
