networks:
  default:
    external: true
    name: traefik

services:
  calibre:
    image: lscr.io/linuxserver/calibre-web:latest
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
    volumes:
      - /share/hhartmann/var/calibre/config:/config
      - /share/hhartmann/garage/Library:/books/garage:ro
      - /share/hhartmann/attic/Books:/books/attic:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.rule=HostRegexp(`books.{domain:.*}`)"
      - "traefik.http.routers.calibre.entrypoints=https"
      - "traefik.http.routers.calibre.tls=true"
