version: "3.9"

services:
  telegram_bot:
    container_name: telegram_bot
    image: docker.heinrichhartmann.net/telegram_bot:latest
    env_file: env.crypt
    volumes:
      - /share/hhartmann/var/paperless/consume/telegram:/work/dl
      - ./cmd.sh:/cmd.sh
    command: /cmd.sh
