version: "3.9"

networks:
  default:
    external: true
    name: traefik

services:
    telegram_bot:
        image: docker.heinrichhartmann.net/telegram_bot:latest
        env_file: env.crypt
        volumes:
        - /share/hhartmann/attic/Stack:/work/dl
        - ./cmd.sh:/cmd.sh
        command: /cmd.sh
