extensions:
  health_check:
  pprof:
  zpages:
  basicauth/otlp:
    client_auth:
      username: 447801
      password: "${env:GRAFANA_CLOUD_KEY}"

receivers:
  # Receivers are available at 192.168.3.3
  otlp:
    protocols:
      grpc: # port 4317
      http: # port 4318

  # Used by treafik
  jaeger:
    protocols:
      thrift_compact: # port 6831
      thrift_http: # port 14268

  # Used by docker host
  fluentforward/docker:
    endpoint: 0.0.0.0:8006

  # Used by systemd
  fluentforward/systemd:
    endpoint: 0.0.0.0:8007

  loki:
    protocols:
      http:
        endpoint: 0.0.0.0:3100

processors:
  batch:
  attributes/loki:
    actions:
      - action: upsert
        key: source
        value: loki
      - action: insert
        key: loki.attribute.labels
        value: unit, hostname, container_name, source, compose_project, compose_service
  attributes/fluent_docker:
    actions:
      - action: upsert
        key: source
        value: docker
      - action: insert
        key: loki.attribute.labels
        value: unit, hostname, container_name, source, fluent.tag
  attributes/fluent_systemd:
    actions:
      - action: upsert
        key: source
        value: systemd
      - action: insert
        key: loki.attribute.labels
        value: unit, hostname, container_name, source, fluent.tag

exporters:
  # print to console
  logging:
    loglevel: info

  logging/debug:
    loglevel: debug

  file:
    path: /var/otel/otel-collector.log
    flush_interval: 1s

  # send to jaeger.heinrichhartmann.net
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  # send to local loki/Grafana
  loki:
    endpoint: "http://192.168.3.4:3100/loki/api/v1/push"

  # send to Grafana Cloud
  otlphttp/grafanacloud:
    auth:
      authenticator: basicauth/otlp
    endpoint: "https://otlp-gateway-prod-eu-west-0.grafana.net/otlp"

  # For some reason otlp/grafanacloud does reject the logs. We use a loki exporter instead
  loki/grafanacloud:
    endpoint: ${env:GRAFANA_CLOUD_LOKI_URL}

  # send to LightStep Saas
  otlp/ls:
     endpoint: ingest.lightstep.com:443
     headers:
       "lightstep-access-token" : ${env:LIGHTSTEP_TOKEN}

service:
  extensions: [health_check, pprof, zpages, basicauth/otlp]
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [batch]
      exporters: [otlp/jaeger, otlphttp/grafanacloud, otlp/ls]
    logs/docker:
      receivers: [fluentforward/docker]
      processors: [batch, attributes/fluent_docker]
      exporters: [loki, loki/grafanacloud]
    logs/systemd:
      receivers: [fluentforward/systemd]
      processors: [batch, attributes/fluent_systemd]
      exporters: [loki, loki/grafanacloud]
    logs/loki:
      receivers: [loki]
      processors: [batch, attributes/loki]
      exporters: [loki, otlphttp/grafanacloud]
    logs/otel:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, otlphttp/grafanacloud]
