version: "3.9"

networks:
  default:
    external: true
    name: traefik

services:
  %HOST%:
    image: ubuntu
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.%HOST%.rule=HostRegexp(`%HOST%.{domain:.*}`)"
      - "traefik.http.routers.%HOST%.entrypoints=https"
      - "traefik.http.routers.%HOST%.tls=true"
