version: "3.9"

networks:
  default:
    external: true
    name: "monitoring"
  traefik:
    external: true
    name: traefik

services:
  telegraf:
    image: telegraf:1.25-alpine
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  influxdb:
     image: influxdb:latest
     networks:
       - default
       - traefik
     volumes:
       - ./influx-config.yml:/etc/influxdb2/config.yml:ro
       - /share/hhartmann/var/influxdb:/var/lib/influxdb2
     labels:
       - 'traefik.http.routers.influxdb.rule=HostRegexp(`influxdb.{domain:.*}`)'
       - 'traefik.http.routers.influxdb.entrypoints=https'
       - 'traefik.http.routers.influxdb.tls=true'
       - 'traefik.enable=true'
