global:
  scrape_interval:     1m
  evaluation_interval: 1m
  external_labels:
      monitor: 'Alertmanager'

rule_files:
    - 'alert.rules'

scrape_configs:
  - job_name: 'mqtt'
    honor_timestamps: false
    static_configs:
         - targets: ['hifipi.ts.heinrichhartmann.net:9641']

  - job_name: 'prometheus'
    static_configs:
         - targets: ['prometheus:9090']

  - job_name: 'nodeexp'
    scrape_interval: 15s
    scrape_timeout: 14s
    static_configs:
    - targets: ['pve.ts.heinrichhartmann.net:9100', 'hifipi.ts.heinrichhartmann.net:9100']

  - job_name: 'speedtest'
    metrics_path: /metrics
    scrape_interval: 30m
    scrape_timeout: 60s # running speedtest needs time to complete
    static_configs:
      - targets: ['speedtest-exporter:9798']

  - job_name: 'traefik'
    static_configs:
    - targets: ['traefik:8082']

  - job_name: 'docker'
    static_configs:
    - targets: ['pve.ts.heinrichhartmann.net:9323']

  - job_name: 'blackbox'
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [svc_http]
    file_sd_configs:
      - files:
        - pinghosts.yaml
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*)'  #first is the url, thus unique for instance
        target_label: instance
        replacement: $1
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*)'  #second is humanname to use in charts
        target_label: humanname
        replacement: $2
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*)'  #third state whether this is testing external or internal network
        target_label: routing
        replacement: $3
      - source_labels: [instance]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.

  - job_name: "blackbox-tcp"
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [tcp_connect]
      target: ['samba.heinrichhartmann.net:445']
    static_configs:
      - targets : ['blackbox-exporter:9115']
        labels:
          humanname: "samba"
          routing: "internal"
          instance: "samba.heinrichhartmann.net:445"


  - job_name: "blackbox-ping"
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          # Syntax: <instance>;<humanname>;<routing>
          - '192.168.2.1;Router;internal'
          - '1.1.1.1;CloudFlare DNS;external'
          - '8.8.8.8;Google DNS;external'
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*)'
        target_label: instance
        replacement: $1
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*)'
        target_label: humanname
        replacement: $2
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*)'
        target_label: routing
        replacement: $3
      - source_labels: [instance]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: "blackbox-ping-lan"
    scrape_interval: 60s
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files:
        - ping-lan.yaml
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*)'
        target_label: instance
        replacement: $1
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*)'
        target_label: humanname
        replacement: $2
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*)'
        target_label: routing
        replacement: $3
      - source_labels: [instance]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: cadvisor
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: otel-collector
    scrape_interval: 15s
    static_configs:
    - targets: ['otel-collector:8888']

tracing:
  endpoint: "otel-collector:4317"
  insecure: true
