version: "3.9"

volumes:
  fbdata:

networks:
  default:
    external: true
    name: traefik

services:
  focalboard:
    image: mattermost/focalboard
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.focalboard.rule=HostRegexp(`focalboard.{domain:.*}`)"
      - "traefik.http.routers.focalboard.entrypoints=https"
      - "traefik.http.routers.focalboard.tls=true"
    volumes:
      - fbdata:/opt/focalboard/data
    environment:
      - VIRTUAL_HOST=focalboard.heinrichhartmann.net
      - VIRTUAL_PORT=8000
