networks:
  default:
    name: "monitoring"
  traefik:
    external: true
    name: traefik
  hostbridge:
    name: "hostbridge"
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
          gateway: 192.168.3.1

services:
  #
  # Data Collectors
  #
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: [--config=/otel/otel-collector-config.yaml]
    env_file:
      - ./otel/otel-collector.env.crypt
    networks:
      default:
      traefik:
      hostbridge:
        ipv4_address: 192.168.3.3
    volumes:
      - ./otel:/otel
      - /share/hhartmann/var/otel:/var/otel
    labels:
      - 'traefik.http.routers.otel-collector.rule=HostRegexp(`otel-collector.{domain:.*}`)'
      - 'traefik.http.routers.otel-collector.entrypoints=https'
      - 'traefik.http.routers.otel-collector.tls=true'
      - 'traefik.enable=true'
      - 'traefik.http.services.otel-collector.loadbalancer.server.port=55679' # zpages
      - 'traefik.docker.network=traefik'

  prometheus:
    container_name: prometheus
    image: 'prom/prometheus:latest'
    networks:
      - default
      - traefik
    labels:
      - 'traefik.http.routers.prometheus.rule=HostRegexp(`prometheus.{domain:.*}`)'
      - 'traefik.http.routers.prometheus.entrypoints=https'
      - 'traefik.http.routers.prometheus.tls=true'
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
    volumes:
      - './prometheus/:/etc/prometheus/'
      - '/share/hhartmann/var/prometheus:/prometheus'


  #
  # Data Sources
  #
  speedtest-exporter:
    container_name: speedtest-exporter
    image: miguelndecarvalho/speedtest-exporter

  blackbox-exporter:
    container_name: blackbox-exporter
    image: prom/blackbox-exporter
    volumes:
      - './blackbox/blackbox.yml:/blackbox/blackbox.yml'
    command:
      - '--config.file=/blackbox/blackbox.yml'

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    networks:
      - default
      - traefik
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - "--housekeeping_interval=30s"
      - "--docker_only=true"
      - "--disable_metrics=percpu,sched,tcp,udp,disk,diskIO,accelerator,hugetlb,referenced_memory,cpu_topology,resctrl"


  #
  # Data Storage
  #
  loki:
    image: grafana/loki:2.8.0
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      default:
      traefik:
      hostbridge:
        ipv4_address: 192.168.3.4
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml
      - /share/hhartmann/var/loki:/var/loki


  #
  # Data Visualization
  #
  grafana:
    # image: grafana/grafana
    build:
      context: ./
      dockerfile: ./grafana/Dockerfile
    networks:
      - default
      - traefik
    labels:
      - 'traefik.http.routers.grafana.rule=HostRegexp(`grafana.{domain:.*}`)'
      - traefik.http.routers.grafana.entrypoints=https
      - traefik.http.routers.grafana.tls=true
      - traefik.enable=true
      - traefik.docker.network=traefik
    volumes:
      - '/share/hhartmann/var/grafana:/var/lib/grafana'
      - './grafana/provisioning/:/etc/grafana/provisioning/'
      - './grafana/grafana.ini:/etc/grafana/grafana.ini'
