version: "3.9"

networks:
  default:
    external: true
    name: "monitoring"
  traefik:
    external: true
    name: traefik
  hostbridge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
          gateway: 192.168.3.1

services:
  #
  # Data Sources
  #
  speedtest-exporter:
    container_name: speedtest-exporter
    image: miguelndecarvalho/speedtest-exporter

  blackbox-exporter:
    container_name: blackbox-exporter
    image: prom/blackbox-exporter
    volumes:
      - './blackbox/config:/config'
    command:
      - '--config.file=/config/blackbox.yml'

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    networks:
      - default
      - traefik
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - "--housekeeping_interval=30s"
      - "--docker_only=true"
      - "--disable_metrics=percpu,sched,tcp,udp,disk,diskIO,accelerator,hugetlb,referenced_memory,cpu_topology,resctrl"

  #
  # Data Collectors
  #
  prometheus:
    container_name: prometheus
    image: 'prom/prometheus:v2.25.2'
    networks:
      - default
      - traefik
    labels:
      - 'traefik.http.routers.prometheus.rule=HostRegexp(`prometheus.{domain:.*}`)'
      - 'traefik.http.routers.prometheus.entrypoints=https'
      - 'traefik.http.routers.prometheus.tls=true'
      - 'traefik.http.routers.prometheus.middlewares=auth@file'
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
    volumes:
      - './prometheus/:/etc/prometheus/'
      - '/share/hhartmann/var/prometheus:/prometheus'

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: [--config=/otel/otel-collector-config.yaml]
    env_file:
      - ./otel/otel-collector.env.crypt
    networks:
      default:
      traefik:
      hostbridge:
        ipv4_address: 192.168.3.3
    volumes:
      - ./otel:/otel
      - /svc/var/otel:/var/otel
    depends_on:
      - jaeger

  #
  # Data Storage
  #
  loki:
    image: grafana/loki:2.8.0
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      default:
      traefik:
      hostbridge:
        ipv4_address: 192.168.3.4
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml

  jaeger:
    image: jaegertracing/all-in-one:1.37
    networks:
      - default
      - traefik
    labels:
      - "traefik.http.routers.jaeger.rule=HostRegexp(`jaeger.{domain:.*}`)"
      - "traefik.http.routers.jaeger.entrypoints=https"
      - "traefik.http.routers.jaeger.tls=true"
      - "traefik.enable=true"
      - "traefik.http.middlewares.auth@file=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.jaeger.loadbalancer.server.port=16686"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true

  #
  # Data Visualization
  #
  grafana:
    image: grafana/grafana
    networks:
      - default
      - traefik
    labels:
      - 'traefik.http.routers.grafana.rule=HostRegexp(`grafana.{domain:.*}`)'
      - traefik.http.routers.grafana.entrypoints=https
      - traefik.http.routers.grafana.tls=true
      - traefik.enable=true
      - traefik.docker.network=traefik
    volumes:
      - '/share/hhartmann/var/grafana:/var/lib/grafana'
      - './grafana/provisioning/:/etc/grafana/provisioning/'
